name: Build Unity AR Android APK

on:
  workflow_dispatch:   # manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Unity
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
          unityVersion: 2021.3  # change to your project’s Unity version
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: AR-APK
          path: build/Android/*.apk
